name = "PidDt"
uuid = "72645456-123f-45ab-8b22-9e45e9948f93"
authors = ["Benjamin Ahlbrecht <BenjaminAhlbrecht@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
